export const metadata = {
    title: 'Sanity',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body suppressHydrationWarning={true}>{children}</body>
        </html>
    )
}
